#
# Verifier options
#
verifier.originalClientId=localhost
verifier.clientIdPrefix=x509_san_dns
verifier.access-certificate.signing-algorithm=ES512
verifier.access-certificate.keystore=classpath:keystore.jks
verifier.access-certificate.keystore.type=jks
verifier.access-certificate.keystore.password=keystore
verifier.access-certificate.alias=access_certificate
verifier.access-certificate.password=access_certificate
