# Enables logging of Mongo mapping events
logging.level.org.springframework=INFO
logging.level.org.springframework.boot.actuate.endpoint.web=DEBUG

management.endpoints.access.default=read_only
spring.web.error.include-stacktrace=ALWAYS
server.port=8080
spring.webflux.static-path-pattern=/public/**
spring.webflux.webjars-path-pattern=/webjars/**
spring.messages.basename=i18n/messages

#
# Verifier options
#
verifier.originalClientId=Verifier
verifier.clientIdPrefix=pre-registered
verifier.access-certificate.signing-algorithm=ES512
verifier.access-certificate.keystore=classpath:keystore.jks
verifier.access-certificate.keystore.type=jks
verifier.access-certificate.keystore.password=keystore
verifier.access-certificate.alias=access_certificate
verifier.access-certificate.password=access_certificate
verifier.publicUrl=http://localhost:${server.port}
verifier.requestJwt.embed=ByReference
verifier.requestJwt.requestUriMethod=Get
verifier.defaultHttpResponseMode=DirectPostJwt
verifier.maxAge=PT6400M
verifier.presentations.cleanup.maxAge=P10D
verifier.authorizationRequestUri=haip-vp://
verifier.allowedRedirectUriSchemes=https

# clientMetadata parameters
verifier.clientMetadata.vpFormats.sdJwtVc.enabled=true
verifier.clientMetadata.vpFormats.sdJwtVc.sdJwtAlgorithms=ES256
verifier.clientMetadata.vpFormats.sdJwtVc.kbJwtAlgorithms=ES256
verifier.clientMetadata.vpFormats.msoMdoc.enabled=true

#
# Configuration parameters for validations applied by verifier
# to wallet presentations or in utilities api
#
verifier.validation.sdJwtVc.statusCheck.enabled=true

# transaction data
verifier.transactionData.hashAlgorithm=sha-256

# cors
cors.origins=*
cors.originPatterns=*
cors.methods=*
cors.headers=*
cors.credentials=false
cors.maxAge=3600

# Trust Validator Service Configuration
#verifier.trust.service-url=https://dev.trust-validator.eudiw.dev/trust

# Attestation Classifications
#verifier.attestation-classifications={"pid":{"vcts":["urn:eudi:pid:1"],"docTypes":["eu.europa.ec.eudi.pid.1"]},"qeaa":{"vcts":[],"docTypes":[]},"pubeaa":{"vcts":[],"docTypes":[]},"eaa":[{"useCase":"mDL","vcts":[],"docTypes":["org.iso.18013.5.1.mDL"]},{"useCase":"learningCredential","vcts":["urn:eu.europa.ec.eudi:learning:credential:1"],"docTypes":[]}]}

# Proxy settings
#verifier.http.proxy.url=http://example.com
#verifier.http.proxy.username=test
#verifier.http.proxy.password=test

# SD-JWT-VC Validation configuration
verifier.validation.sdJwtVc.kbJwt.clock.skew=PT5S

verifier.validation.sdJwtVc.typeMetadata.policy=not-used
#verifier.validation.sdJwtVc.typeMetadata.policy.requiredFor=urn:eudi:pid:1

# SD-JWT VC Type Metadata resolution
verifier.validation.sdJwtVc.typeMetadata.resolution.cache.ttl=PT1H
verifier.validation.sdJwtVc.typeMetadata.resolution.cache.maxEntries=10
verifier.validation.sdJwtVc.typeMetadata.resolution.integrity.enabled=false
verifier.validation.sdJwtVc.typeMetadata.resolution.integrity.allowedAlgorithms=sha256,sha384,sha512
#verifier.validation.sdJwtVc.typeMetadata.resolution.vcts[0].vct=urn:eudi:pid:1
#verifier.validation.sdJwtVc.typeMetadata.resolution.vcts[0].url=https://dev.issuer-backend.eudiw.dev/type-metadata/urn:eudi:pid:1

verifier.registration_certificate[0]=eyJ4NWMiOlsiTUlJQmNUQ0NBUmlnQXdJQkFnSUdBWjlHbC9yaU1Bb0dDQ3FHU000OUJBTUNNRUF4UGpBOEJnTlZCQU1NTlZSbGMzUWdTWE56ZFdWeUlFbHVabThnWXpKa056VmtNMll0TVRWbFpDMDBNemszTFdJeU5HRXRabVk0WkdWbFlUTXlZekJpTUI0WERUSTJNRGN3T1RFeE1UWXpNMW9YRFRJM01EY3dPVEV4TVRZek0xb3dRREUrTUR3R0ExVUVBd3cxVkdWemRDQkpjM04xWlhJZ1NXNW1ieUJqTW1RM05XUXpaaTB4TldWa0xUUXpPVGN0WWpJMFlTMW1aamhrWldWaE16SmpNR0l3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNYNEJjd2JCS2hvVVdqNHhDc2tVZWZPRGczdEhoak5WZjUwZGFmTWpCTkg1SEhyK3UyUXpyZkluNE9KWlc5UEVkbFF3b1ZhSVNRc09odlg5dmxWVW5YTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUd1clFZSmhNcTdGTnZPS3dPZG5Na2UwSExrU2pkY3RJV2hoSGl2U3l3YnJBaUFLdnpzZDgzci9IU3E3aTdRUHJ4dHJvbUEvZ1grMEc5SWFtRjFLdDZ6Ky93PT0iXSwia2lkIjoiYzYzNjgzZjItN2RmMy00M2ZmLWI1MzktZDA3MTk0NDViMGJlIiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2lzc3Vlci5leGFtcGxlIiwic3ViIjoiaXNzdWVyLWluZm8iLCJpYXQiOjE3ODM1OTU3OTJ9.Ai4XydxG__EASIOboGWcPzK2hMTIrHSvGrnT3UhInc8UkXBiCacPgEurYQ9fO6J1fhhX2eRe6t7xRcbT-Rzy-g
verifier.registration-certificate[1]=eyJ4NWMiOlsiTUlJQkhEQ0J4S0FEQWdFQ0FoUmp6T3Z1VUNXNFVieXMyNWgvRndHZlN4SFR1akFLQmdncWhrak9QUVFEQWpBUE1RMHdDd1lEVlFRRERBUjBaWE4wTUI0WERUSTJNRGN4TURBNE1EZ3dOMW9YRFRJM01EY3hNREE0TURnd04xb3dEekVOTUFzR0ExVUVBd3dFZEdWemREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKZlY0dFJ5U1dybTdsVkFTQjk0bUJLTTR3dlBKRkV1S012VWhwcUlyY3JkMkduam1PejJJS3Vrb0tkZVRjbTkzczM5U2w1NHl4UTI0Q3NLTVlmM2t3c3dDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdhdFJ6eUVidklLWk9wNVlyUDlJYW5ScVcyRTk1dC9vM3F1cmV0OXVXY2hrQ0lIcndEQ3dwQlJKNk9LQUNrZmNGRVZvWmNiTTU4NGZpRjVzb2h1TXNLcjg3Il0sInR5cCI6InJjLXdycCtqd3QiLCJhbGciOiJFUzI1NiJ9.eyJuYW1lIjoiS290bGluIElzc3VlciBTaWduZXIgRGV2Iiwic3ViX2xuIjoiTmlzY3kiLCJzdWIiOiJMRUlFVS0xMjM0NTY3ODkiLCJjb3VudHJ5IjoiRVUiLCJyZWdpc3RyeV91cmkiOiJodHRwczovL3JlZ2lzdHJ5LmV4YW1wbGUuZXUiLCJzcnZfZGVzY3JpcHRpb24iOlt7ImxhbmciOiJlbiIsInZhbHVlIjoiQW4gaW1wbGVtZW50YXRpb24gb2YgYSBjcmVkZW50aWFsIGlzc3Vpbmcgc2VydmljZSwgYWNjb3JkaW5nIHRvIE9wZW5JZDRWQ0kgLSB2MS4wIn1dLCJlbnRpdGxlbWVudHMiOlsiaHR0cHM6Ly91cmkuZXRzaS5vcmcvMTk0NzUvRW50aXRsZW1lbnQvUElEX1Byb3ZpZGVyIiwiaHR0cHM6Ly91cmkuZXRzaS5vcmcvMTk0NzUvRW50aXRsZW1lbnQvUUVBQV9Qcm92aWRlciIsImh0dHBzOi8vdXJpLmV0c2kub3JnLzE5NDc1L0VudGl0bGVtZW50L1BVQl9FQUFfUHJvdmlkZXIiXSwicHJpdmFjeV9wb2xpY3kiOiJodHRwczovL2Rldi5pc3N1ZXItYmFja2VuZC5ldWRpdy5kZXYvcHJpdmFjeSIsImluZm9fdXJpIjoiaHR0cHM6Ly9kZXYuaXNzdWVyLWJhY2tlbmQuZXVkaXcuZGV2Iiwic3VwcG9ydF91cmkiOiJodHRwczovL2Rldi5rb3RsaW5Jc3N1ZXJTaWduZXIuY29tL3N1cHBvcnQiLCJzdXBlcnZpc29yeV9hdXRob3JpdHkiOnsiZW1haWwiOiJzdXBlcnZpc29yeUBhdXRob3JpdHkuZXhhbXBsZS5ldSIsInBob25lIjoiKzQ5MzAxMjM0NTY3IiwidXJpIjoiaHR0cHM6Ly9zdXBlcnZpc29yeS5hdXRob3JpdHkuZXhhbXBsZS5ldSJ9LCJwb2xpY3lfaWQiOlsiMC40LjAuMTk0NzUuMy4xIl0sImNlcnRpZmljYXRlX3BvbGljeSI6Imh0dHBzOi8vZXhhbXBsZS5ldS9jZXJ0aWZpY2F0ZS1wb2xpY3kiLCJpYXQiOjE3ODM2ODEwMjgsInN0YXR1cyI6eyJzdGF0dXNfbGlzdCI6eyJpZHgiOjkxMCwidXJpIjoiaHR0cHM6Ly9pc3N1ZXIuZXVkaXcuZGV2L3Rva2VuX3N0YXR1c19saXN0L0VVL2V1LmV1cm9wYS5lYy5ldWRpLnBpZC4xLzIwZWY5ZTk4LTg2NzYtNDViYy04OWJhLTE3MDhmMGYyMTIzOSJ9fSwicHJvdmlkZXNfYXR0ZXN0YXRpb25zIjpbeyJmb3JtYXQiOiJkYytzZC1qd3QiLCJtZXRhIjp7InZjdF92YWx1ZXMiOlsidXJuOmV1ZGk6cGlkOjEiLCJ1cm46ZXUuZXVyb3BhLmVjLmV1ZGk6bGVhcm5pbmc6Y3JlZGVudGlhbDoxIl19fSx7ImZvcm1hdCI6Im1zb19tZG9jIiwibWV0YSI6eyJkb2N0eXBlX3ZhbHVlIjoiZXUuZXVyb3BhLmVjLmV1ZGkucGlkLjEifX0seyJmb3JtYXQiOiJtc29fbWRvYyIsIm1ldGEiOnsiZG9jdHlwZV92YWx1ZSI6Im9yZy5pc28uMTgwMTMuNS4xLm1ETCJ9fV19.h3wtRbSVXVGJVblxwHLQQivFN-iQiyyIGLmbFoNHpC8GRcKjuseUhbatzS-PGh7eDBPOCwh0VSgotEtjTiYKzA
