# Enables logging of Mongo mapping events
logging.level.org.springframework=info

spring.webflux.static-path-pattern=/public/**
spring.webflux.webjars-path-pattern=/webjars/**
spring.messages.basename=i18n/messages

#
# Verifier options
#
verifier.requestJwt.embed=ByReference
verifier.requestJwt.requestUriMethod=Get
verifier.defaultHttpResponseMode=DirectPostJwt
verifier.maxAge=PT6400M
verifier.presentations.cleanup.maxAge=P10D
verifier.allowedRedirectUriSchemes=https

# clientMetadata parameters
verifier.clientMetadata.vpFormats.sdJwtVc.enabled=true
verifier.clientMetadata.vpFormats.sdJwtVc.sdJwtAlgorithms=ES256
verifier.clientMetadata.vpFormats.sdJwtVc.kbJwtAlgorithms=ES256
verifier.clientMetadata.vpFormats.msoMdoc.enabled=true

#
# Configuration parameters for validations applied by verifier
# to wallet presentations or in utilities api
#
verifier.validation.sdJwtVc.statusCheck.enabled=true

# SD-JWT-VC Validation configuration
verifier.validation.sdJwtVc.kbJwt.clock.skew=PT5S

# transaction data
verifier.transactionData.hashAlgorithm=sha-256

# cors
cors.origins=*
cors.originPatterns=*
cors.methods=*
cors.headers=*
cors.credentials=false
cors.maxAge=3600


# Proxy settings
#verifier.http.proxy.url=http://example.com
#verifier.http.proxy.username=test
#verifier.http.proxy.password=test
